### ISSUE TITLE
while loops

### ISSUE THREAD

**Issue by deniederhut** [deniederhut/workshop_pyintensive#2]
It might be cool, as a sort of a mid-class test/challenge in day one, to have the students rewrite one of your `for` loop examples using only `while`. E.g.:

```
text_var = 'berkeley'
i = 0
while i < len(text_var):
    print(text_var[i])
    i += 1
```

BTW your stuff looks great so far!

**Comment by juanshishido** [comment]
Just saw this. I'll incorporate this!

Thanks for the feedback. Feels like it's a _lot_, but we can always cut it back a bit if needed :)
