### ISSUE TITLE
Standardized publicity text

### ISSUE THREAD

**Issue by davclark** [deniederhut/workshop_pyintensive#4]
I'd argue that "everything" should be in once place. More specifically, here.

We're talking about standardizing workshop production, and it seems like we should have all the things that go into the D-Lab website, emails, etc. here.

Am I wrong?

**Comment by deniederhut** [comment]
You are not wrong - that would be super useful for me. I am less certain that Trin or Colleen would find it to be as helpful.

**Comment by deniederhut** [comment]
@davclark I know Github automatically renders README and CONTRIBUTING - are there similar conventions for announcements, maybe that show up as OpenGraph cards?

**Comment by davclark** [comment]
Yeah - I was talking to Patty and Susan about this, and probably we should use the workshop production teams standards. I don't know exactly what they are, but let's figure it out?

For OpenGraph, I guess you could use something like Zapier. But probably this is best done with javascript in a website, and then you just have whatever conventions you support in a defined file - accessible via a URL. That could be a fun thing to experiment with in the dlab-berkeley.github.io site.
