### ISSUE TITLE
Extra day for python instruction?

### ISSUE THREAD

**Issue by deniederhut** [deniederhut/workshop_pyintensive#6]
How would we feel about adding a fifth day (day 4) to explicitly cover:
1. architecture (e.g. clean code, code complete)
2. modularity (unix philosophy, functional programming)
3. python class structure (self, **init**, _, __) 
4. python idioms (e.g. decorators, generators, context managers)
5. testing

Organized under the theme of "okay, so you can write legal python code, now let's walk through how to write good python code"

**Comment by juanshishido** [comment]
@deniederhut I think that's a fantastic idea! We can get some PEP8 into the mix&mdash;[this](https://github.com/amontalenti/elements-of-python-style) is also a great resource, IMO&mdash;as well as testing with, perhaps, `doctest`, `nose`, or `pytest`.

Might we want to also touch on way**s** to organize repositories? Or ways to package code for distribution?
