### ISSUE TITLE
Python instructors team name

### ISSUE THREAD

**Issue by deniederhut** [deniederhut/workshop_pyintensive#7]
Current contenders are:
1. Pythonistas
2. The Charmers
3. Snakes on a Plane
4. Cobra Command
5. Hydra
   (Thanks to @camillevilla for those last three)

@davclark @juanshishido @marwahaha and Chris (I couldn't find your GH account) - feel free to submit more names for consideration, and please record your votes below.

**Comment by juanshishido** [comment]
+1 for Hydra

![hydra](https://cloud.githubusercontent.com/assets/7218875/12900604/0ed47b48-ce6c-11e5-800e-8529706e34c4.png)

**Comment by deniederhut** [comment]
@henchc

**Comment by henchc** [comment]
I agree with Hydra, very clever.

**Comment by juanshishido** [comment]
Hail Hydra!

**Comment by juanshishido** [comment]
@deniederhut, @henchc, @camillevilla, @marwahaha: Wow

![hail-hydra](https://cloud.githubusercontent.com/assets/7218875/15546740/e8be9a54-2255-11e6-9614-cef0e49bd2d4.jpg)

_(Photo: Marvel Comics)_

http://www.usatoday.com/story/life/2016/05/25/captain-america-comic-book-reveal/84896522/

**Comment by deniederhut** [comment]
Mwahaha mine is an evil laugh
